<a href="https://colab.research.google.com/github/sinman96/Code-used-for-dissertation/blob/master/Flight_fare_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import matplotlib as plt
import pandas as pd
from flight_project_functions import *
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)

df = pd.read_csv('itineraries.csv')
print(len(df))
df.head(10)
df = df.dropna()
print(len(df))
print(df.columns)
df.head(10)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (8,9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


1095181
1010044
Index(['legId', 'searchDate', 'flightDate', 'startingAirport',
       'destinationAirport', 'fareBasisCode', 'travelDuration', 'elapsedDays',
       'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare',
       'seatsRemaining', 'totalTravelDistance',
       'segmentsDepartureTimeEpochSeconds', 'segmentsDepartureTimeRaw',
       'segmentsArrivalTimeEpochSeconds', 'segmentsArrivalTimeRaw',
       'segmentsArrivalAirportCode', 'segmentsDepartureAirportCode',
       'segmentsAirlineName', 'segmentsAirlineCode',
       'segmentsEquipmentDescription', 'segmentsDurationInSeconds',
       'segmentsDistance', 'segmentsCabinCode'],
      dtype='object')


legId  searchDate  flightDate startingAirport  \
0   9ca0e81111c683bec1012473feefd28f  2022-04-16  2022-04-17             ATL   
1   98685953630e772a098941b71906592b  2022-04-16  2022-04-17             ATL   
2   98d90cbc32bfbb05c2fc32897c7c1087  2022-04-16  2022-04-17             ATL   
3   969a269d38eae583f455486fa90877b4  2022-04-16  2022-04-17             ATL   
4   980370cf27c89b40d2833a1d5afc9751  2022-04-16  2022-04-17             ATL   
6   9335fae376c38bb61263281779f469ec  2022-04-16  2022-04-17             ATL   
7   3904bf87f2d1daf334f1ae7e3b876028  2022-04-16  2022-04-17             ATL   
8   d93988734c44a3c075d9efe373352507  2022-04-16  2022-04-17             ATL   
9   562e7d5dd6ecbf1509c0c19711dbdca9  2022-04-16  2022-04-17             ATL   
10  c38a6e4b807d15541e5866676febcbec  2022-04-16  2022-04-17             ATL   

   destinationAirport fareBasisCode travelDuration  elapsedDays  \
0                 BOS      LA0NX0MC        PT2H29M          0.0   
1                 BOS      LA0NX0MC        PT2H30M          0.0   
2                 BOS      LA0NX0MC        PT2H30M          0.0   
3                 BOS      LA0NX0MC        PT2H32M          0.0   
4                 BOS      LA0NX0MC        PT2H34M          0.0   
6                 BOS      V0AJZNN1        PT4H12M          0.0   
7                 BOS      V0AJZNN1        PT5H18M          0.0   
8                 BOS      V0AJZNN1        PT5H32M          0.0   
9                 BOS      V0AJZNN1        PT6H38M          0.0   
10                BOS      VAA0AKEN        PT4H46M          0.0   

   isBasicEconomy isRefundable  ... segmentsArrivalTimeEpochSeconds  \
0           False        False  ...                      1650223560   
1           False        False  ...                      1650200400   
2           False        False  ...                      1650218700   
3           False        False  ...                      1650227460   
4           False        False  ...                      1650213180   
6           False        False  ...          1650203400||1650213120   
7           False        False  ...          1650203400||1650217080   
8           False        False  ...          1650198060||1650213120   
9           False        False  ...          1650198060||1650217080   
10          False        False  ...          1650194280||1650204960   

                               segmentsArrivalTimeRaw  \
0                       2022-04-17T15:26:00.000-04:00   
1                       2022-04-17T09:00:00.000-04:00   
2                       2022-04-17T14:05:00.000-04:00   
3                       2022-04-17T16:31:00.000-04:00   
4                       2022-04-17T12:33:00.000-04:00   
6   2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...   
7   2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...   
8   2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...   
9   2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...   
10  2022-04-17T07:18:00.000-04:00||2022-04-17T10:1...   

    segmentsArrivalAirportCode  segmentsDepartureAirportCode  \
0                          BOS                           ATL   
1                          BOS                           ATL   
2                          BOS                           ATL   
3                          BOS                           ATL   
4                          BOS                           ATL   
6                     CLT||BOS                      ATL||CLT   
7                     CLT||BOS                      ATL||CLT   
8                     CLT||BOS                      ATL||CLT   
9                     CLT||BOS                      ATL||CLT   
10                    IAD||BOS                      ATL||IAD   

                     segmentsAirlineName segmentsAirlineCode  \
0                                  Delta                  DL   
1                                  Delta                  DL   
2                                  Delta                  DL   
3                                  Delta 

FEATURE ENGINEERING AND SELECTION

In [23]:
df = df.drop(columns = 
['legId','fareBasisCode', 'travelDuration', 'segmentsDistance'], axis = 1)
print(df.isnull().sum())
print(df.nunique()) 
df.head(10)

searchDate                           0
flightDate                           0
startingAirport                      0
destinationAirport                   0
elapsedDays                          0
isBasicEconomy                       0
isRefundable                         0
isNonStop                            0
baseFare                             0
totalFare                            0
seatsRemaining                       0
totalTravelDistance                  0
segmentsDepartureTimeEpochSeconds    0
segmentsDepartureTimeRaw             0
segmentsArrivalTimeEpochSeconds      0
segmentsArrivalTimeRaw               0
segmentsArrivalAirportCode           0
segmentsDepartureAirportCode         0
segmentsAirlineName                  0
segmentsAirlineCode                  0
segmentsEquipmentDescription         0
segmentsDurationInSeconds            0
segmentsCabinCode                    0
dtype: int64
searchDate                                4
flightDate                               61
st

searchDate  flightDate startingAirport destinationAirport  elapsedDays  \
0   2022-04-16  2022-04-17             ATL                BOS          0.0   
1   2022-04-16  2022-04-17             ATL                BOS          0.0   
2   2022-04-16  2022-04-17             ATL                BOS          0.0   
3   2022-04-16  2022-04-17             ATL                BOS          0.0   
4   2022-04-16  2022-04-17             ATL                BOS          0.0   
6   2022-04-16  2022-04-17             ATL                BOS          0.0   
7   2022-04-16  2022-04-17             ATL                BOS          0.0   
8   2022-04-16  2022-04-17             ATL                BOS          0.0   
9   2022-04-16  2022-04-17             ATL                BOS          0.0   
10  2022-04-16  2022-04-17             ATL                BOS          0.0   

   isBasicEconomy isRefundable isNonStop  baseFare  totalFare  ...  \
0           False        False      True    217.67      248.6  ...   
1           False        False      True    217.67      248.6  ...   
2           False        False      True    217.67      248.6  ...   
3           False        False      True    217.67      248.6  ...   
4           False        False      True    217.67      248.6  ...   
6           False        False     False    213.02      251.1  ...   
7           False        False     False    213.02      251.1  ...   
8           False        False     False    213.02      251.1  ...   
9           False        False     False    213.02      251.1  ...   
10          False        False     False    213.02      252.6  ...   

                             segmentsDepartureTimeRaw  \
0                       2022-04-17T12:57:00.000-04:00   
1                       2022-04-17T06:30:00.000-04:00   
2                       2022-04-17T11:35:00.000-04:00   
3                       2022-04-17T13:59:00.000-04:00   
4                       2022-04-17T09:59:00.000-04:00   
6   2022-04-17T08:20:00.000-04:00||2022-04-17T10:2...   
7   2022-04-17T08:20:00.000-04:00||2022-04-17T11:2...   
8   2022-04-17T07:00:00.000-04:00||2022-04-17T10:2...   
9   2022-04-17T07:00:00.000-04:00||2022-04-17T11:2...   
10  2022-04-17T05:30:00.000-04:00||2022-04-17T08:3...   

    segmentsArrivalTimeEpochSeconds  \
0                        1650223560   
1                        1650200400   
2                        1650218700   
3                        1650227460   
4                        1650213180   
6            1650203400||1650213120   
7            1650203400||1650217080   
8            1650198060||1650213120   
9            1650198060||1650217080   
10           1650194280||1650204960   

                               segmentsArrivalTimeRaw  \
0                       2022-04-17T15:26:00.000-04:00   
1                       2022-04-17T09:00:00.000-04:00   
2                       2022-04-17T14:05:00.000-04:00   
3                       2022-04-17T16:31:00.000-04:00   
4                       2022-04-17T12:33:00.000-04:00   
6   2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...   
7   2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...   
8   2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...   
9   2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...   
10  2022-04-17T07:18:00.000-04:00||2022-04-17T10:1...   

   segmentsArrivalAirportCode segmentsDepartureAirportCode  \
0                         BOS                          ATL   
1                         BOS                          ATL   
2                         BOS                          ATL   
3                         BOS                          ATL   
4                         BOS                          ATL   
6                    CLT||BOS                     ATL||CLT   
7                    CLT||BOS                     ATL||CLT   
8                    CLT||BOS                     ATL||CLT   
9                    CLT||BOS                     ATL||CLT   
10                   IAD||BOS                     ATL||IAD   

     

df['segmentsDurationInSeconds'] = df['segmentsArrivalTimeEpochSeconds'] - df['segmentsDepartureTimeEpochSeconds'] so I will drop segmentsArrivalTimeEpochSeconds and segmentsDepartureTimeEpochSeconds

In [24]:
df = df.drop(columns =
['segmentsArrivalTimeEpochSeconds','segmentsDepartureTimeEpochSeconds'], axis = 1)
df['segmentsDurationInSeconds'] = df['segmentsDurationInSeconds'].apply(total_seconds)
df['segmentsDurationInHours'] = df['segmentsDurationInSeconds']/3600
df = df.drop(columns = ['segmentsDurationInSeconds'], axis = 1)
x = df['isBasicEconomy'].values
df['isBasicEconomy']=np.select([x == False, x == True], [0,1])
x = df['isRefundable'].values
df['isRefundable']=np.select([x == False, x == True], [0,1])
x = df['isNonStop'].values
df['isNonStop']=np.select([x == False, x == True], [0,1])
df['searchDate'] = df['searchDate'].astype('datetime64[ns]')
df['flightDate'] = df['flightDate'].astype('datetime64[ns]')
df['daysUntilFlight'] = df['flightDate'] - df['searchDate']
df = df.drop(columns = ['flightDate','searchDate'], axis = 1)
df['daysUntilFlight'] = df['daysUntilFlight'].astype('str')
df['daysUntilFlight'] = df['daysUntilFlight'].apply(lambda x: int(x[0]))
df= df[df['seatsRemaining'] > 0]
df['segmentsCabinCode'] = df['segmentsCabinCode'].apply(total_changes)
df['numberOfChanges'] = df['segmentsCabinCode'] - 1
df = df.drop(columns =
['segmentsCabinCode', 'segmentsAirlineCode'], axis = 1)

In [25]:
df = df.drop(columns = ['segmentsDepartureAirportCode'], axis = 1)
df = df.drop(columns = ['segmentsArrivalAirportCode'], axis = 1)
df['arrivalTimeToNearestHour'] = df['segmentsDepartureTimeRaw'].apply(nearest_hour_of_day)
df['departureTimeToNearestHour'] = df['segmentsArrivalTimeRaw'].apply(nearest_hour_of_day)
df = df.drop(columns = ['segmentsDepartureTimeRaw', 'segmentsArrivalTimeRaw'], axis = 1)
df = df.rename(columns={'segmentsAirlineName': "airlineName", 'segmentsEquipmentDescription': "equipmentDescription",
'segmentsDurationInHours': 'durationInHours'})
print(df.columns)
df['%IncreaseFromBaseFare'] = 100*(df['totalFare'] - df['baseFare'])/df['totalFare'] 
x = df['%IncreaseFromBaseFare']
df['%IncreaseFromBaseFare'] = np.select([x < 10, x >= 10], [0,1])
df.head(10)

Index(['startingAirport', 'destinationAirport', 'elapsedDays',
       'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare',
       'seatsRemaining', 'totalTravelDistance', 'airlineName',
       'equipmentDescription', 'durationInHours', 'daysUntilFlight',
       'numberOfChanges', 'arrivalTimeToNearestHour',
       'departureTimeToNearestHour'],
      dtype='object')


startingAirport destinationAirport  elapsedDays  isBasicEconomy  \
0              ATL                BOS          0.0               0   
1              ATL                BOS          0.0               0   
2              ATL                BOS          0.0               0   
3              ATL                BOS          0.0               0   
4              ATL                BOS          0.0               0   
6              ATL                BOS          0.0               0   
7              ATL                BOS          0.0               0   
8              ATL                BOS          0.0               0   
9              ATL                BOS          0.0               0   
10             ATL                BOS          0.0               0   

    isRefundable  isNonStop  baseFare  totalFare  seatsRemaining  \
0              0          1    217.67      248.6             9.0   
1              0          1    217.67      248.6             4.0   
2              0          1    217.67      248.6             9.0   
3              0          1    217.67      248.6             8.0   
4              0          1    217.67      248.6             9.0   
6              0          0    213.02      251.1             3.0   
7              0          0    213.02      251.1             3.0   
8              0          0    213.02      251.1             7.0   
9              0          0    213.02      251.1             7.0   
10             0          0    213.02      252.6             1.0   

    totalTravelDistance                           airlineName  \
0                 947.0                                 Delta   
1                 947.0                                 Delta   
2                 947.0                                 Delta   
3                 947.0                                 Delta   
4                 947.0                                 Delta   
6                 956.0  American Airlines||American Airlines   
7                 956.0  American Airlines||American Airlines   
8                 956.0  American Airlines||American Airlines   
9                 956.0  American Airlines||American Airlines   
10                947.0                        United||United   

           equipmentDescription  durationInHours  daysUntilFlight  \
0                   Airbus A321         2.483333                1   
1                   Airbus A321         2.500000                1   
2                Boeing 757-200         2.500000                1   
3                   Airbus A321         2.533333                1   
4                   Airbus A321         2.566667                1   
6      Airbus A320||Airbus A320         3.583333                1   
7   Airbus A320||Boeing 737-800         3.800000                1   
8      Airbus A319||Airbus A320         3.433333                1   
9   Airbus A319||Boeing 737-800         3.650000                1   
10  Airbus A319||Boeing 737-800         3.450000                1   

    numberOfChanges  arrivalTimeToNearestHour  departureTimeToNearestHour  \
0                 0                      13.0                        15.0   
1                 0                       6.5                         9.0   
2                 0                      12.0                        14.0   
3                 0                      14.0                        17.0   
4                 0                      10.0                        13.0   
6                 1                       8.0                        10.0   
7                 1                       8.0                        10.0   
8                 1                       7.0                         8.0   
9                 1                       7.0                         8.0   
10                1                       5.5                         7.0   

    %IncreaseFromBaseFare  
0                       1  
1                       1  
2                       1  
3                       1  
4                  

In [26]:
df = df.drop(columns = ['startingAirport', 'destinationAirport', 'airlineName',
       'equipmentDescription'], axis = 1)
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(X)

[[ 0.   0.   0.  ...  0.  13.  15. ]
 [ 0.   0.   0.  ...  0.   6.5  9. ]
 [ 0.   0.   0.  ...  0.  12.  14. ]
 ...
 [ 0.   1.   0.  ...  0.  16.  19. ]
 [ 0.   1.   0.  ...  0.  18.  20.5]
 [ 0.   1.   0.  ...  0.  20.  23. ]]


USING XGBOOST TO PREDICT FARES FARE INCREASE CLASSIFICATIONS

In [27]:
"""## Splitting the dataset into the Training set and Test set"""
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size = 0.25, random_state = 0)
 
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

"""## Making the Confusion Matrix"""
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

"""## Applying K-Fold Cross Validation##"""
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

[[ 12063    376]
 [   480 239592]]
0.996610048671147
Accuracy: 99.67 %
Standard Deviation: 0.01 %


In [28]:
"""Using XGBoost regression to predict total fares"""
warnings.filterwarnings("ignore", category=DeprecationWarning) 
X = df.drop(columns = ['totalFare', '%IncreaseFromBaseFare'], axis = 1).values
y = df[['totalFare']].values

"""## Splitting the dataset into the Training set and Test set"""
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size = 0.25, random_state = 0)
 
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE of total fare predictions is: ${:.2f}".format(rmse))

[16:57:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE of total fare predictions is: $3.13


LOGISTIC REGRESSION PREDICTING DIRECT FLIGHTS

In [29]:
"""## Applying Logistic Regression to separate direct and non direct flights##"""
X = df[['totalFare', 'durationInHours']].values
y = df[['isNonStop']].values
print(X)
print(y)
y = y.reshape(len(y), 1)
#Splitting into Test and Train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X)
print(y)
#Importing Support vector Regression and fitting the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', random_state = 0)
model.fit(X_train, y_train)
#Predict a random pair
print(model.predict(sc.transform([[350,2.5]])))
#Predicting the test set results
y_pred = model.predict(X_test)
#Make confusion matrix to determine accuracy of matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[248.6          2.48333333]
 [248.6          2.5       ]
 [248.6          2.5       ]
 ...
 [153.6          2.48333333]
 [153.6          2.5       ]
 [153.6          2.56666667]]
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[[248.6          2.48333333]
 [248.6          2.5       ]
 [248.6          2.5       ]
 ...
 [153.6          2.48333333]
 [153.6          2.5       ]
 [153.6          2.56666667]]
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[1]
[[168940  12834]
 [ 25366  45371]]
0.8487194617264199
